name: { { project_name.snakeCase() } }
description: This project includes every useful thing that i use in other flutter projects
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  api_service:
    path: /Users/tokenizer/Projects/flutter/packages/api_service
  auto_route: ^5.0.4
  bloc: ^8.1.0
  crypto: ^3.0.2
  dartz: ^0.10.1
  database_service:
    path: /Users/tokenizer/Projects/flutter/packages/database_service
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  number_paginator:
    path: /Users/tokenizer/Projects/flutter/packages/number_paginator
  persian_datetime_picker: ^2.5.0
  responsive_framework: ^0.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  #image_path: "assets/images/png/ic_launcher.png"
  #image_path_ios: "assets/images/png/ic_launcher.png"

flutter:
  uses-material-design: true
  generate: true

assets:
  - assets/
  - assets/images/

fonts:
  - family: iranYekanWeb
    fonts:
      - asset: assets/fonts/Iranyekan thin.ttf
        weight: 200
      - asset: assets/fonts/Iranyekan light.ttf
        weight: 300
      - asset: assets/fonts/Iranyekan.ttf
        weight: 400
      - asset: assets/fonts/Iranyekan medium.ttf
        weight: 500
      - asset: assets/fonts/Iranyekan bold.ttf
        weight: 700
      - asset: assets/fonts/Iranyekan black.ttf
        weight: 800
